### ISSUE TITLE
provide CDN bundle

### ISSUE THREAD

**Issue by airtonix** [inca/voie#11]
So far your build tool only outputs a collection of files that use `require`  statements.

Output something that results in : 
- one file, absent of `require` statements would help us provide jsfiddles, jsbins, codepens or whatever for the purpose of nailing down isolated examples of bugs.
- one file that uses commonjs require statements
- one file that uses plain es6

This file would be hosted somewhere like `cdnjs` or whatever.

It'd also help out those who don't wish to bundle voie.js in their output bundles.

update: meant to say please :)

**Comment by jonagoldman** [comment]
A dist folder has been added and you can reference the file directly (for development only). I think we can close this issue.
