### ISSUE TITLE
Question: 'enter' hook from inside a component

### ISSUE THREAD

**Issue by jonagoldman** [inca/voie#14]
Is there a way to use use the 'enter' hook inside a component instead of the state?

```js
// SomeComponent.vue
export default {
  
  enter: (ctx) => {
    return fetch('/user/' + ctx.params.userId)
      .then(res => res.json())
      .then(data = ctx.data.user = data);
  }

}

// Voie state
app.add('user', {
  path: '/user',
  component: SomeComponent
});
```

**Comment by inca** [comment]
I was thinking about the same thing the other day: to provide a shorthand configuration just like in your example (or even `app.add('state', MyVueComponent)`), just had concerns about introducing multiple ways to do the same thing — and potential ambiguities introduced by this decision (e.g. if enter specified both on state and component, which of the two to use?).

So I really don't mind implementing that, just curious whether we should do it in api-breaking way, or just support it as a fallback and issue warnings if same configuration provided twice. What do you think?

**Comment by jonagoldman** [comment]
In one hand, hooks logically belongs more to the state than to the component.
On the other hand, in real world scenarios, hooks have an important job that is logically related to the component. Check user permissions, fetch required data, etc... Those methods are generally encapsulated in a service or other kind of abstraction layer. A lot of times, those services are also needed inside the component, so you end up requiring the same service in the state and in the component. You split the logic in two separate files, making it more difficult to see the whole picture.
To illustrate the problem:

```js
// Voie state
import 'userService' from './userService'

app.add('user', {
  path: '/user',
  enter: (ctx) => {
    return myService.getUser(ctx.params.userId)
      .then(res => res.json())
      .then(data = ctx.data.user = data);
  },
  component: UserComponent
});

// UserComponent.vue
import 'userService' from './userService'

export default {  
  methods: {

}
}


```

**Comment by jonagoldman** [comment]
It might be better to have everything under a 'voie' object:

```js
export default {
   voie: {
      enter: //,
      leave: //,
      redirect: //
   }
}
```

and this also opens up to possibility to use the new Vuex API:

```js
export default {
   vuex: {
      state: //,
      actions: //
   },
   voie: {
      enter: // use vuex state and actions,
      leave: //,
      redirect: //
   }
}
```

**Comment by inca** [comment]
@jonagoldman makes complete sense. However, I might still need to ponder a bit on api, contracts for hooks and specific use-cases (e.g. do we need to bind `this` inside component's `enter` hook to actual vm instance?)

**Comment by jonagoldman** [comment]
In my example I use ``this`` inside the hook as a best case scenario where I can access Vuex state and actions directly. I don't know if this is possible. If its not then I can use a service, but having access to Vuex is powerful, for example:

```js
import { getResources } from './store/actions'

export default {

   vuex: {
      state: {
         isLoggedIn: state => state.auth.isLoggedIn
      },
      actions: {
        getResources
      }
   },

   voie: {
      enter: ctx => {
        if (!this.isLoggedIn) {
          return { redirect: 'login' };
        }
        else {
          return this.getResources();
        }
      }
   }

}
```

I hope I am not asking too much, I'm just giving the best solution for me.

**Comment by inca** [comment]
Just a bump: I didn't forget about this one, just thinking over the whole context/data propagation thing — and whether some ground-breaking changes can be avoided or not.

**Comment by jonagoldman** [comment]
Sure. Also take a look at this https://github.com/vuejs/vuex/issues/84.

**Comment by jonagoldman** [comment]
Hey @inca have you thought about this?

**Comment by inca** [comment]
Yep, sorry for such a long reply. Unfortunately, I currently see no way of allowing component instance access inside enter because of current design (e.g. enter hook can also [return another component](https://github.com/inca/voie/blob/master/test/specs/transitions.js#L97)), so accessing `this` in `enter` hooks is not possible.

As for `enter` methods available "statically", they seem to add two points of confusion:

  1. one would naturally assume the valid use of `this` inside these hooks, which is not possible
  2. non-obvious order of execution if `enter` is also declared on state (but we could as well forbid that and throw exceptions to only allow one hook)

**Comment by jonagoldman** [comment]
I understand, same thing in vue-router, the component instance is not available inside the hook.
