### ISSUE TITLE
Voie 0.6.5 Babel "import" Unexpected token

### ISSUE THREAD

**Issue by Teknologica** [inca/voie#16]
I was in the middle of creating a custom `v-link` directive for my project's special needs when I noticed the manager events changed in the most recent version. So I upgraded to `0.6.5` from `0.5.4` (voie-starter-webpack package.json has that version) and suddenly Babel stopped working. Ironically this is the same error I was having 3 weeks ago when trying to run Voie without using the starter. 

I haven't been able to tell what changed between the two versions that breaks Babel. Maybe you have some insights @inca ?

**Comment by Teknologica** [comment]
Found a clue. I compared webpack configs between `voie-starter-webpack` and mine and I noticed the starter is using this loader: 
```js
{
	test: /\.js$/,
	loader: 'babel',
	include: /src/
}
```
While I was using 
```js
{
	test: /\.js$/,
	loader: 'babel',
	exclude: /node_modules/
},
```
I switched my exclude to the include above and now it compiles. I have to check if the rest still works.

**Comment by Teknologica** [comment]
@inca 
Update: if you try to use the official `vue-webpack-boilerplate` with Voie the `import` error occurs. 
```
Module parse failed: [...]\node_modules\voie\src\index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import StateManager from './state-manager';
| import State from './state';
| import Transition from './transition';
 @ ./src/main.js 7:12-27
```
This is using `0.6.5` and the [webpack template for Vue](https://github.com/vuejs-templates/webpack#vue-webpack-boilerplate).

**Comment by Teknologica** [comment]
Found a similar issue on the Webpack repo: [Webpack fails to build ES6 in external packages](https://github.com/webpack/webpack/issues/2017)

**Comment by Teknologica** [comment]
So my fix for this issue is to define the `voie` source folder as an include for the `babel` loader
```js
{
    test: /\.js$/,
    loader: 'babel',
    include: [
        projectRoot,
        //explicitly include ES6 modules
        path.resolve(__dirname, '../../node_modules/voie/src')
    ]
},
```
It took me a while to understand the issue but I see now why it failed and it's definitely a feature I wasn't using right. :smile:

**Comment by anlek** [comment]
I'm having the same issue but I don't know where to put this code above. @Teknologica Where did you place this code?
Thanks,
Andrew

**Comment by Teknologica** [comment]
@anlek You have to define that as module loader in the webpack configuration. Basically `Voie` is written as ES6 so in order for Webpack to pack it correctly it has to be processed by Babel first otherwise it won't understand the package and throw that `import` token error. 

This is an abridged configuration for my webpack.
```js
module: {
    loaders: [
        {
            test: /\.vue$/,
            loader: 'vue'
        },
        {
            test: /\.js$/,
            loader: 'babel',
            include: [
                //only parsing project source path 
                applicationSource,
                //explicitly include ES6 modules
                path.resolve(__dirname, '../../node_modules/voie/src')
            ]
        }
    }
}
```

**Comment by anlek** [comment]
Hmm, still no go, here is what I have

```javascript
// see http://vuejs-templates.github.io/webpack for documentation.
var path = require('path')

module.exports = {
  build: {
    index: path.resolve(__dirname, 'dist/index.html'),
    assetsRoot: path.resolve(__dirname, 'dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    productionSourceMap: true
  },
  dev: {
    port: 8080,
    proxyTable: {}
  },
  module: {
    loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
    {
        test: /\.js$/,
        loader: 'babel',
        include: [
          //only parsing project source path
          './src/',
          //explicitly include ES6 modules
          path.resolve(__dirname, '/node_modules/voie/src/')
        ]
      }
    ]
  }
}
```

**Comment by Teknologica** [comment]
@anlek that looks different than mine. I've used the official template for the setup too. Did you use `vue-cli` command to setup your project? My config is very similar to the [one they provide in the template repo](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js). I have a common (shared) config, then two separate overwrites for private (local) testing and production. 
If you use the https://github.com/vuejs-templates/webpack template and try without `Voie` to make sure it works then define the `include` for the `babel` loader to force it to parse as ES6 it should work. That was the starting point for me and I've customized everything from there.

**Comment by anlek** [comment]
Right, it seems I was editing the wrong file. I finally got it working.
Thanks for your help!

**Comment by anlek** [comment]
Seemed to have caused issue due to my exclude line, so this is how my config looks like:

```javascript
loaders: [
      {
        test: /\.vue$/,
        loader: 'vue'
      },
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules\/(?!voie)/,
        include: [
          projectRoot,
          path.resolve(__dirname, '../node_modules/voie/src')
        ]

      }
]
```
