### ISSUE TITLE
Global hooks

### ISSUE THREAD

**Issue by jonagoldman** [inca/voie#19]
I'm developing an app where I need to check if the user has permissions to access each state.
Right now I'm doing the check in each 'enter' hook.
Would be useful to have a global hook / middleware so I can just check in one place.

**Comment by inca** [comment]
So you're looking for something like `beforeEach` with access to state-specific contexts? I assume the global ancestor state like `authenticated` from which all protected states inherit doesn't satisfy your needs?

**Comment by jonagoldman** [comment]
Yes, ``beforeEach`` or similar.
Because this is how my app looks now:

```js
// 'settings' state
enter: (ctx) => {
    if ( ! permissionService.userCan('access_settings')) {
        return { redirect: 'app' };
    }
}

// 'billing' state
enter: (ctx) => {
    if ( ! permissionService.userCan('access_billing')) {
        return { redirect: 'app' };
    }
}

// and so on...
```

A global hook can simplify this.
What do you think?

**Comment by Teknologica** [comment]
I had to do something similar. I created a function that wraps around the StateManager `add` to handle permissions automatically. It also wraps around any other `enter` delegates that get defined and daisy chains them. 

```js
Router.add({
    name: 'dashboard',
    path: '/dashboard',
    parent: 'main',
    checkPermissions: false, // adds a predefined enter permission check if true
    component: DashboardView
});
```

**Comment by inca** [comment]
Hey, `beforeEach` and `afterEach` are available in 0.7.0, let me know if they work as you expect them to ;)

**Comment by jonagoldman** [comment]
haha great! will try it in the next few days.

**Comment by jonagoldman** [comment]
Seems to work perfectly, thanks!
By the way, I see the 0.7.0 release in npm but not in GitHub releases. Are you using master as latest release?
