### ISSUE TITLE
How to get query string params?

### ISSUE THREAD

**Issue by anh** [inca/voie#3]
Reading the API I don't know how to get query string params, is there anyway to get those params on ctx object.

**Comment by inca** [comment]
Full query params support is in to-do list, right now you can use [history](https://github.com/rackt/history) to parse query string for you. Or even grab something like query-string or qs for that, although I'd recommend to wait for full support.

**Comment by inca** [comment]
I'll reopen this if you don't mind — and will update as basic query support is implemented.

**Comment by anh** [comment]
Awesome, thank you, I'll try it, I closed it for I saw it was already on Todo list. Voie is great I like it a lot.
