### ISSUE TITLE
Main entrance point to the app

### ISSUE THREAD

**Issue by jonagoldman** [inca/voie#4]
I see you don't import Vue in any of the examples, and that its being imported by StateManager for internal use.

Does this affects the way I should work with Vue in any way?

Based on your live example, should I use the [app.js] (https://github.com/inca/voie-example/blob/master/spa/app.js) file as the main entrance point for all the app or should I leave that for state management only and import Vue in a different component?

In my case I want to use  Voie with [Vuex] (https://github.com/vuejs/vuex), so I need to set ```Vue.use(Vuex)``` somewhere and was wondering where is the correct place to do it.

**Comment by inca** [comment]
Hi, sure, you can import `Vue` before `StateManager`, b/c doesn't rely on any Vue internals.

Modules load ordering is not important, so something like this will do the trick:

```es6
import Vue from 'vue';
import Vuex from 'vuex'
import { StateManager } from 'voie';

Vue.use(Vuex);
// Create state manager
```

**Comment by inca** [comment]
Re: live example, we used `app.js` only to export default state manager singleton. Entry point in the sample app is [index.js](https://github.com/inca/voie-example/blob/master/spa/index.js) — app is loaded and started there.

**Comment by jonagoldman** [comment]
Thanks for the fast reply! It makes sense.
I have a more specific question related to Vuex so I will open a separate issue.
